Fix content extraction
skyshard/snacktory pull request #31
Opened 2017-05-18 12:23 UTC by abhishek-airpr

----
https://www.nytimes.com/2017/05/17/us/politics/robert-mueller-special-counsel-russia-investigation.html
- Extra text was getting fetched in article body
- Added rules in setToRemove to exclude unwanted elements

----
http://nymag.com/daily/intelligencer/2017/04/march-jobs-report-falls-short-of-expectations.html
- Quoted text was not extracted
- Added rule in nodesToKeepCssSelector

----
http://blog.dogsbite.org/2014/08/014-dog-bite-fatality-toddler-dies-family-pit-bull-attack-under-grandmothers-care.html
- Ignored wrong TestCase

----
http://www.delish.com/cooking/g2668/spring-asparagus-dishes/
http://www.delish.com/cooking/g2669/breakfast-casserole-recipes/
- Assign the description as a content if article doen't have content at all

2017-05-19 18:58 UTC, andresp99999 commented on src/main/java/de/jetwick/snacktory/ArticleTextExtractor.java
> +        elems = doc.select("body > div:nth-child(7) > div > div.col-sm-9 > div > h1 > span > p > span");
I wonder if we can do as a last resort some sort of search for common dates format in the article body. Ideally we don't to get this specific when defining rules (although in some cases we may have not option).

2017-05-19 19:37 UTC, skyshard commented on src/main/java/de/jetwick/snacktory/ArticleTextExtractor.java
> +        elems = doc.select("body > div:nth-child(7) > div > div.col-sm-9 > div > h1 > span > p > span");
yes, this is way too specific/brittle of a selector, we might not want to merge this in favor of that date checking rule instead

2017-05-20 00:15 UTC, skyshard requested changes

2017-05-20 00:15 UTC, skyshard commented on src/main/java/de/jetwick/snacktory/ArticleTextExtractor.java
> +        elems = doc.select("body > div:nth-child(7) > div > div.col-sm-9 > div > h1 > span > p > span");
let's move this specific case out, the rest can be merged

2017-05-23 02:03 UTC, abhishek-airpr commented
@skyshard Addressed review comments. Consider merging this if no more action item.

2017-05-24 17:00 UTC, merged