Fixed author/content extraction
skyshard/snacktory pull request #32
Opened 2017-05-22 09:14 UTC by abhishek-airpr

----
http://redhat.sys-con.com/node/4068643
Before:
"author": "ManageEngine IT Matters"
"author_description": "By ManageEngine IT Matters"

Now:
"author": "Elizabeth White"
"author_description": "http://elizabethwhite.sys-con.com/",

----
http://www.sltrib.com/home/5252884-155/vivint-smart-home-links-with-best
- Fixed content extraction - Missing few paragraphs
- Added rules in BEST_ELEMENT_PER_DOMAIN and setToRemove

----
http://therivardreport.com/san-antonio-space-scientists-prepare-for-jupiter-contact-1/
- Fixed content extraction - Removed excessive contents
- Added rules in NODES_TO_REMOVE_PER_DOMAIN

2017-05-24 17:09 UTC, skyshard requested changes

2017-05-24 17:09 UTC, skyshard commented on src/main/java/de/jetwick/snacktory/ArticleTextExtractor.java
> +            Matcher macher = DOMAIN_WITHOUT_TLD.matcher(domain);
typo

2017-05-24 17:09 UTC, skyshard commented on src/main/java/de/jetwick/snacktory/ArticleTextExtractor.java
> +    private static final Pattern WAYFAIR_DATE_PATTERN = Pattern.compile("\"display_date\":\"([^\"]+)\"");
Make this more extensible across different sites

2017-05-24 17:09 UTC, skyshard commented on src/main/java/de/jetwick/snacktory/ArticleTextExtractor.java
> +    private static final Pattern DOMAIN_WITHOUT_TLD = Pattern.compile("(www\\.)?([^\\.]+).*");
Does this work on domains with multiple subdomains

2017-05-25 05:36 UTC, abhishek-airpr commented on src/main/java/de/jetwick/snacktory/ArticleTextExtractor.java
> +    private static final Pattern DOMAIN_WITHOUT_TLD = Pattern.compile("(www\\.)?([^\\.]+).*");
In fact no. But the regex used in extractDomainNameWithoutTld accepts the privateTopLevelDomain which doesn't have subdomains in it.

2017-05-25 05:36 UTC, abhishek-airpr commented on src/main/java/de/jetwick/snacktory/ArticleTextExtractor.java
> +    private static final Pattern DOMAIN_WITHOUT_TLD = Pattern.compile("(www\\.)?([^\\.]+).*");
Adding necessary comment in method documentation

2017-05-25 08:30 UTC, abhishek-airpr commented
@skyshard Please recheck the suggested changes.

2017-05-31 00:06 UTC, merged