Fix extraction issues
skyshard/snacktory pull request #42
Opened 2017-06-15 10:15 UTC by abhishek-airpr

----
CRAW-208: http://www.nydailynews.com/newswires/sports/kershaw-wins-bellinger-hits-2-homers-dodgers-top-indians-article-1.3245615

Before:
"author": "",
"author_description": "",

Now:
"author": "The Associated Press",
"author_description": "THE ASSOCIATED PRESS",

----
CRAW-203: https://www.ft.com/content/d0a5c460-5044-11e7-a1f2-db19572361bb

Before:
"author":"",
"author_description":"",

Now:
"author": "Michael Power"
"author_description": "by: Michael Power, Investec"

----
CRAW-211: http://sdn.cioreview.com/cxoinsight/sdn-do-you-really-need-it-nid-24422-cid-147.html

Before:
"author": "CIO Review"
"author_description": "CIO Review"

Now:
"author": "Patrick Hubbard"
"author_description": "Patrick Hubbard, Head Geek, SolarWinds"

2017-06-15 17:17 UTC, andresp99999 commented on src/main/java/de/jetwick/snacktory/ArticleTextExtractor.java
> +            return SHelper.innerTrim(matches.first().ownText());
Maybe add a DEBUG_AUTHOR_EXTRACTION log here?

2017-06-16 16:34 UTC, skyshard requested changes

2017-06-16 16:34 UTC, skyshard commented on src/main/java/de/jetwick/snacktory/ArticleTextExtractor.java
> +                        matches = doc.select("p > strong:contains(By)");
This looks like it would be a slow selector

2017-06-16 16:41 UTC, abhishek-airpr commented on src/main/java/de/jetwick/snacktory/ArticleTextExtractor.java
> +                        matches = doc.select("p > strong:contains(By)");
@skyshard  The article uses pretty much plain html tags without distinguishing css.

2017-06-19 14:57 UTC, abhishek-airpr commented on src/main/java/de/jetwick/snacktory/ArticleTextExtractor.java
> +                        matches = doc.select("p > strong:contains(By)");
@skyshard - Can you confirm what can be done here? Should we merge this as is or remove fix for nation.foxnews.com?

2017-06-22 16:57 UTC, andresp99999 commented on src/main/java/de/jetwick/snacktory/ArticleTextExtractor.java
> +                        matches = doc.select("p > strong:contains(By)");
@abhishek-airpr let's remove the nation.foxnews.com hack for now, after that feel free to merge it.

2017-06-22 17:36 UTC, merged